<a href="https://colab.research.google.com/github/VishnuK-0206/AIML-IIITH/blob/main/Broadcasting_assign1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Broadcasting

It allows arrays of different shapes and dimensions to be combined in arithmetic operations without the need for explicit copying or reshaping of data. Broadcasting rules automatically perform element-wise operations between arrays with compatible shapes, making code more concise and efficient.

1.Scalar-Array Broadcasting:

This involves combining a scalar (single value) with an array of any shape. The scalar value is broadcasted to match the shape of the array, and then element-wise operations are performed.

In [3]:
import numpy as np

scalar = 5
array = np.array([[1, 2], [3, 4]])
result = scalar * array
print(result)


[[ 5 10]
 [15 20]]


2.Array-Array Broadcasting:

When performing operations between arrays of different shapes, broadcasting can occur if their shapes are compatible. Broadcasting rules dictate how dimensions are expanded to match the shape of the larger array.

In [4]:
import numpy as np

array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5]])
result = array1 + array2
print(result)

[[5 6 7]
 [6 7 8]]


3.Higher-Dimensional Broadcasting:

Broadcasting extends to higher-dimensional arrays as well. Arrays with different numbers of dimensions can be broadcasted if their trailing dimensions are compatible.

In [5]:
import numpy as np

array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Shape: (2, 2, 2)
array2 = np.array([10, 20])                             # Shape: (2,)
result = array1 + array2[:, np.newaxis, np.newaxis]
print(result)

[[[11 12]
  [13 14]]

 [[25 26]
  [27 28]]]
